"""CashProof Domain layer: pure domain models, financial calculations, and deterministic rules."""

from cashproof.domain.ai import (
    Investigation,
    InvestigatorBudget,
    ResolutionProposal,
    ToolCallRecord,
)
from cashproof.domain.decision import (
    AuditEvent,
    BridgeSnapshot,
    GateCheckOutcome,
    GateEvaluation,
    Resolution,
    evaluate_gate,
    validate_ledger_target_exclusivity,
)
from cashproof.domain.derived import (
    Evidence,
    EvidencePointer,
    MatchCandidate,
    ReconciliationCase,
)
from cashproof.domain.exceptions import (
    CurrencyMismatchError,
    DirectConstructionForbiddenError,
    DomainError,
    DuplicateRefundNettingError,
    EmptySettlementItemsError,
    GateEvaluationIntegrityError,
    InvalidStateTransitionError,
    LedgerEntryAlreadyResolvedError,
    MonetaryInvariantError,
    RefundNettingMismatchError,
    ResolutionGateViolationError,
    ResolutionGovernanceError,
    ResolutionScopeMismatchError,
    ResolutionTargetMismatchError,
    SettlementAssociationError,
    SettlementItemBridgeError,
    SettlementItemSumMismatchError,
)
from cashproof.domain.money import (
    aggregate_ledger_total,
    calculate_gst_on_fee,
    calculate_ledger_signed_amount,
    calculate_settlement_item_net,
    compute_case_delta,
)
from cashproof.domain.source import (
    LedgerEntry,
    Payment,
    Refund,
    Settlement,
    SettlementItem,
    validate_refund_netting_invariant,
    validate_settlement_items_aggregation,
)
from cashproof.domain.state import (
    VALID_TRANSITIONS,
    transition_state,
)
from cashproof.domain.types import (
    AuditActor,
    Currency,
    Direction,
    Disposition,
    EvidenceStance,
    ExceptionType,
    HypothesisSource,
    MatchProvenance,
    PaymentStatus,
    ProcessingState,
    RefundStatus,
    ReviewOutcome,
    StopReason,
)

__version__ = "0.1.0"

__all__ = [
    "AuditEvent",
    "AuditActor",
    "BridgeSnapshot",
    "Currency",
    "CurrencyMismatchError",
    "DirectConstructionForbiddenError",
    "Direction",
    "Disposition",
    "DomainError",
    "DuplicateRefundNettingError",
    "EmptySettlementItemsError",
    "Evidence",
    "EvidencePointer",
    "EvidenceStance",
    "ExceptionType",
    "GateCheckOutcome",
    "GateEvaluation",
    "GateEvaluationIntegrityError",
    "HypothesisSource",
    "InvalidStateTransitionError",
    "Investigation",
    "InvestigatorBudget",
    "LedgerEntry",
    "LedgerEntryAlreadyResolvedError",
    "MatchCandidate",
    "MatchProvenance",
    "MonetaryInvariantError",
    "Payment",
    "PaymentStatus",
    "ProcessingState",
    "ReconciliationCase",
    "Refund",
    "RefundNettingMismatchError",
    "RefundStatus",
    "Resolution",
    "ResolutionGateViolationError",
    "ResolutionGovernanceError",
    "ResolutionProposal",
    "ResolutionScopeMismatchError",
    "ResolutionTargetMismatchError",
    "ReviewOutcome",
    "Settlement",
    "SettlementAssociationError",
    "SettlementItem",
    "SettlementItemBridgeError",
    "SettlementItemSumMismatchError",
    "StopReason",
    "ToolCallRecord",
    "VALID_TRANSITIONS",
    "aggregate_ledger_total",
    "calculate_gst_on_fee",
    "calculate_ledger_signed_amount",
    "calculate_settlement_item_net",
    "compute_case_delta",
    "evaluate_gate",
    "transition_state",
    "validate_ledger_target_exclusivity",
    "validate_refund_netting_invariant",
    "validate_settlement_items_aggregation",
]
