"""CashProof Derived Reconciliation Artifacts.

Immutable domain representations of evidence, match candidates, and reconciliation cases.
"""

from __future__ import annotations

import math
from collections.abc import Iterable, Sequence
from dataclasses import dataclass

from cashproof.domain.source import (
    Settlement,
    SettlementItem,
    validate_settlement_items_aggregation,
)
from cashproof.domain.types import (
    EvidenceStance,
    ExceptionType,
    MatchProvenance,
    ProcessingState,
)


@dataclass(frozen=True, slots=True)
class EvidencePointer:
    """Field-level pointer to source evidence."""

    entity_type: str
    entity_id: str
    field: str

    def __post_init__(self) -> None:
        if not self.entity_type.strip():
            raise ValueError("EvidencePointer entity_type must not be empty.")
        if not self.entity_id.strip():
            raise ValueError("EvidencePointer entity_id must not be empty.")
        if not self.field.strip():
            raise ValueError("EvidencePointer field must not be empty.")


@dataclass(frozen=True, slots=True)
class Evidence:
    """Immutable evidence unit with pointer, relevance, and stance."""

    pointer: EvidencePointer
    relevance: float
    stance: EvidenceStance
    decision_consumed: bool = False

    def __post_init__(self) -> None:
        if math.isnan(self.relevance) or math.isinf(self.relevance):
            raise ValueError("relevance must be a finite float.")
        if not (0.0 <= self.relevance <= 1.0):
            raise ValueError(f"relevance must be between 0.0 and 1.0, got {self.relevance}")


@dataclass(frozen=True, slots=True)
class MatchCandidate:
    """Immutable candidate match generated by deterministic matching rules.

    Candidate scores never authorize resolution on their own.
    """

    case_id: str
    ledger_entry_id: str
    score: float
    matched_signals: tuple[str, ...]
    rule_trace: tuple[str, ...]
    provenance: MatchProvenance
    engine_version: str
    run_id: str

    def __init__(
        self,
        case_id: str,
        ledger_entry_id: str,
        score: float,
        matched_signals: Iterable[str],
        rule_trace: Iterable[str],
        provenance: MatchProvenance,
        engine_version: str,
        run_id: str,
    ) -> None:
        if not case_id.strip():
            raise ValueError("case_id must not be empty.")
        if not ledger_entry_id.strip():
            raise ValueError("ledger_entry_id must not be empty.")
        if math.isnan(score) or math.isinf(score):
            raise ValueError("score must be a finite float.")
        if not (0.0 <= score <= 1.0):
            raise ValueError(f"score must be between 0.0 and 1.0, got {score}")
        if not engine_version.strip():
            raise ValueError("engine_version must not be empty.")
        if not run_id.strip():
            raise ValueError("run_id must not be empty.")

        object.__setattr__(self, "case_id", case_id)
        object.__setattr__(self, "ledger_entry_id", ledger_entry_id)
        object.__setattr__(self, "score", float(score))
        object.__setattr__(self, "matched_signals", tuple(matched_signals))
        object.__setattr__(self, "rule_trace", tuple(rule_trace))
        object.__setattr__(self, "provenance", provenance)
        object.__setattr__(self, "engine_version", engine_version)
        object.__setattr__(self, "run_id", run_id)


@dataclass(frozen=True, slots=True)
class ReconciliationCase:
    """Immutable unit of reconciliation work for a settlement instance."""

    case_id: str
    settlement_id: str
    run_id: str
    expected_net: int
    observed_ledger_total: int
    delta: int
    exception_type: ExceptionType
    processing_state: ProcessingState = ProcessingState.INGESTED

    def __post_init__(self) -> None:
        if not self.case_id.strip():
            raise ValueError("case_id must not be empty.")
        if not self.settlement_id.strip():
            raise ValueError("settlement_id must not be empty.")
        if not self.run_id.strip():
            raise ValueError("run_id must not be empty.")
        expected_delta = self.expected_net - self.observed_ledger_total
        if self.delta != expected_delta:
            raise ValueError(
                f"delta ({self.delta}) != expected_net - observed_ledger_total ({expected_delta})"
            )

    @classmethod
    def create(
        cls,
        case_id: str,
        settlement: Settlement,
        items: Sequence[SettlementItem],
        observed_ledger_total: int,
        exception_type: ExceptionType,
        run_id: str,
    ) -> ReconciliationCase:
        """Authoritative factory that validates settlement item aggregation before case creation."""
        validate_settlement_items_aggregation(settlement, items)
        expected_net = settlement.net_deposited_minor
        delta = expected_net - observed_ledger_total
        return cls(
            case_id=case_id,
            settlement_id=settlement.settlement_id,
            run_id=run_id,
            expected_net=expected_net,
            observed_ledger_total=observed_ledger_total,
            delta=delta,
            exception_type=exception_type,
            processing_state=ProcessingState.INGESTED,
        )
